### ISSUE TITLE
memory average

### ISSUE THREAD

**Issue by Kikobeats** [jub3i/node-mem-stat#2]
I love this library! I'm trying to design something similar to cpu load average [1, 5, 15] but based on memory.

Any idea about how to do it?

**Comment by jub3i** [comment]
@Kikobeats glad you like the library, i had alot of fun making all the *-stat libraries :D

if you want 1, 5 and 10 minute averages, you could for example, 
- store `usedPercent()` reading every 10 seconds (using somthing like `setInterval()`) (perhaps make the sampling rate configurable) 
- keep at most 60 readings (10 minutes/10 seconds interval = 60 readings), maybe a FIFO queue data structure with a max length
- then average them out appropriately to get your [1min , 5min ,10min] averages

you could turn it into a module and call it `mem-avg`, ive checked and its not taken on npm ;)

the cpu load averages linux uses are a little more in depth than just regular averages described above, check out http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages

**Comment by Kikobeats** [comment]
My first idea was something similar to your words, using setInterval. The problem with that is the process doesn't exit because is waiting the interval.

the advante of load average is that read from a system file `/proc/loadavg`. I'm going to build a "stateless" similar solution (for example, you are reading from `/proc/meminfo`).

I don't know if a UNIX system have a proc file for this purpose or I can create one 🤔
